version: '3'

services:

  diploma-db:
    image: postgres:latest
    container_name: diploma-db
    environment:
      POSTGRES_DB: diploma
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    command: -c 'shared_buffers=256MB' -c 'max_locks_per_transaction=1024'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
